<a href="https://colab.research.google.com/github/depeshsikarwar/Data-Science/blob/main/lec06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [75]:
import pandas as pd

In [2]:
df=pd.read_csv("student_data.csv")
print(df)

      study_hours  attendance  sleep_hours  internet_usage  \
0               7          56            8               7
1               4          69            5               3
2              11          60            7               6
3               8          99            9               8
4               5          52            8               6
...           ...         ...          ...             ...
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
0                        10              62      100.00           Placed
1                         8              56      100.00           Placed
2                        10              45      100.00           Placed
3                         4              55       90.17           Placed
4                         8              40       78.82           Placed
...                     ...             ...         ...              ...
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

[10000 rows x 8 columns]

In [6]:
print(df.head())
print("\n")
print()
print(df.tail())

   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8
4            5          52            8               6

   assignments_completed  previous_score  exam_score placement_status
0                     10              62      100.00           Placed
1                      8              56      100.00           Placed
2                     10              45      100.00           Placed
3                      4              55       90.17           Placed
4                      8              40       78.82           Placed



      study_hours  attendance  sleep_hours  internet_usage  \
9995            2          58            9               7
9996            7          98            6               9
9997           10          44            8               5
9998           10          75            7               5
9999            2          70            6              11

      assignments_completed  previous_score  exam_score placement_status
9995                      8              88       69.31       Not Placed
9996                      4              87      100.00           Placed
9997                     10              37       95.94           Placed
9998                      8              52       88.61           Placed
9999                     16              52       78.96           Placed

In [17]:
dct={
    'name':["lanchenba","Nick","Jagjeet","Krish"],
    'age':[20,21,19,76],
    'roll':[1,2,3,4]
}
df1=pd.DataFrame(dct,index=['a','b','c','d'])
print(dct,"\n")
# df1
# it not display two by default it print only last one
display(df1)
df1

{'name': ['lanchenba', 'Nick', 'Jagjeet', 'Krish'], 'age': [20, 21, 19, 76], 'roll': [1, 2, 3, 4]}

        name  age  roll
a  lanchenba   20     1
b       Nick   21     2
c    Jagjeet   19     3
d      Krish   76     4

        name  age  roll
a  lanchenba   20     1
b       Nick   21     2
c    Jagjeet   19     3
d      Krish   76     4

In [25]:
# for shape
df.shape
# info give meta data
# metadata is the data of the real data
df.info()
# Describe
df.describe()
# IQR=q3-q1
# Q1 is the median from 0 to till the median term
# Q2 is the median of the sorted data
# q3 is the median from full data median to the end
df.columns
df.index

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

RangeIndex(start=0, stop=10000, step=1)

In [46]:
# Data Munipulation
display(df[['study_hours','exam_score','internet_usage']])

df['study_hours']

      study_hours  exam_score  internet_usage
0               7      100.00               7
1               4      100.00               3
2              11      100.00               6
3               8       90.17               8
4               5       78.82               6
...           ...         ...             ...
9995            2       69.31               7
9996            7      100.00               9
9997           10       95.94               5
9998           10       88.61               5
9999            2       78.96              11

[10000 rows x 3 columns]

0        7
1        4
2       11
3        8
4        5
        ..
9995     2
9996     7
9997    10
9998    10
9999     2
Name: study_hours, Length: 10000, dtype: int64

In [50]:
# row manupulation
# display(df.iloc[0:100:5])
df.loc[df['study_hours']==11,['sleep_hours','study_hours']].iloc[4:8]

     sleep_hours  study_hours
30             5           11
91             9           11
98             6           11
116            7           11

In [54]:
# df.loc[df['study_hours']==11,['sleep_hours','study_hours']]
df.iloc[0:4,0:4]

   study_hours  attendance  sleep_hours  internet_usage
0            7          56            8               7
1            4          69            5               3
2           11          60            7               6
3            8          99            9               8

In [56]:
df.loc[df['assignments_completed']==8].iloc[2]

study_hours                   4
attendance                   98
sleep_hours                   9
internet_usage                2
assignments_completed         8
previous_score               70
exam_score                100.0
placement_status         Placed
Name: 13, dtype: object

In [62]:
# df.loc[df['assignments_completed']>3]
# df[df['assignments_completed']>3]
df['age']=20
df

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [69]:

# df=df.rename(columns={'assignments_completed':'assignment completed'})
df.rename(columns={'assignments_completed':'assign_completed'}, inplace=True)
df
# it change data not change original return new dataframe

,study_hours,attendance,sleep_hours,internet_usage,assignment cpmpleted,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [77]:
df = pd.read_csv("student_data.csv")
df.rename(columns={'assignments_completed':'assign_completed'},inplace=True)
df

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [96]:
df = pd.read_csv("student_data.csv")
# df.drop(['study_hours','internet_usage'],axis=1,inplace=True)
df.drop(range(0,5),inplace=True)
df.notnull()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
5,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True
7,True,True,True,True,True,True,True,True
8,True,True,True,True,True,True,True,True
9,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
9995,True,True,True,True,True,True,True,True
9996,True,True,True,True,True,True,True,True
9997,True,True,True,True,True,True,True,True
9998,True,True,True,True,True,True,True,True
9999,True,True,True,True,True,True,True,True

In [95]:
import pandas as pd
dict={
    'name':['depesh','lanchenba','Jagjeet',None],
    'age':[18,20,20,21],
    'Address':['Mathura','Manipur',None,'Patna'],

}
df=pd.DataFrame(dict)
df.dropna(inplace=True)
df

        name  age  Address
0     depesh   18  Mathura
1  lanchenba   20  Manipur